### ISSUE TITLE
Issues with Sky, Seams, and Vertical Look since Dynamic Res commits

### ISSUE THREAD

**Issue by bangstk** [fabiangreffrath/woof#1334]
Built from commit 7e00e9c:
Windows 10 x64 build, Visual Studio 2022

**With 'Double' hires mode, and sometimes in 'High' hires mode (depending on currently active scale) there is an artifact:
A column of HOM on the right of the screen, except sprites will continue to draw there:**
![woof0000](https://github.com/fabiangreffrath/woof/assets/4380573/95d2dc16-fd3b-409b-904e-2bdb1b726f26)

This happens with any window size or fullscreen (though for more info my monitor's aspect ratio is 16:9 at 2560x1440)
It's still there on the side of game content if the window is stretched wide.
It goes away if Widescreen is turned off or hires setting is "Triple" or  "Original" scale.

**Also, there is now a line at the top of skies in any hires mode "Double" and up.**
![woof0001](https://github.com/fabiangreffrath/woof/assets/4380573/b13b763b-6f7c-4475-bd0e-02ec9660cbc3)

Additionally, **"Linear sky scrolling" appears to have no effect** since these commits (the sky is always warped as it reaches the edges)

Finally, **if player is looking up or down, the vertical angle jumps around as the scale factor changes.**
This happens as you cycle through "Single" "Double" "Triple", and it also happens in "High" mode whenever the scale dynamically changes with performance.
Disorienting if it happens during live gameplay. It doesn't seem to affect direct aim point (your view is just shifted away from it as the scale changes)
This didn't happen when switching hires mode between "on" and "off in previous versions.

**Comment by rfomin** [comment]
> With 'Double' hires mode, and sometimes in 'High' hires mode (depending on currently active scale) there is an artifact:
> A column of HOM on the right of the screen, except sprites will continue to draw there:

Hopefully fixed there: https://github.com/fabiangreffrath/woof/commit/39017451432ae7a8705ad1ee3bb0486584c1a474

> Also, there is now a line at the top of skies in any hires mode "Double" and up.

Fixed here: https://github.com/fabiangreffrath/woof/commit/7535a5dae72223c2f2b965832efbffbb917b6776

> "Linear sky scrolling" appears to have no effect

Fixed here: https://github.com/fabiangreffrath/woof/commit/834c10510ca193aa9ce684b24eff43d83f729359

> Finally, if player is looking up or down, the vertical angle jumps around as the scale factor changes.

Hmm, it seems I can't replicate it or didn't understand it.

**Comment by bangstk** [comment]
Here's a clip of what I mean with the view angle
Looking all the way up and down and changing scale from double to triple makes the angle change a decent amount.
https://github.com/fabiangreffrath/woof/assets/4380573/7f150323-5d74-4ddf-a048-57db32ebd739

This also happens as the dynamic res scaling shifts up and down.

A good test for that is Eviternity Map26
Once the start elevator reaches the top, the scale should drop due to the super complex tower in front of you.
Then, turn around, the scale should go back up since you're now looking at a simple building.

Now, do the same while looking all the way up the whole time, you will notice your vertical look position vibrate as the scale changes.

https://www.dropbox.com/home/Public?preview=woof-exe_2023-12-16_04-54-09.mp4
Heres a clip of that, I recommend downloading it to watch to get the full quality.

I looked at the code a little bit and it seems to be "viewblocks" in R_ExecuteSetViewSize not scaling gracefully, at some scales being too big and at others too small.

**Comment by bangstk** [comment]
> > With 'Double' hires mode, and sometimes in 'High' hires mode (depending on currently active scale) there is an artifact:
> > A column of HOM on the right of the screen, except sprites will continue to draw there:
> 
> Hopefully fixed there: [3901745](https://github.com/fabiangreffrath/woof/commit/39017451432ae7a8705ad1ee3bb0486584c1a474)

It's fixed for the non-dynamic modes now, but still can appear in "High" mode depending on the current scale.

**Comment by rfomin** [comment]
> I looked at the code a little bit and it seems to be "viewblocks" in R_ExecuteSetViewSize not scaling gracefully, at some scales being too big and at others too small.

Maybe fixed here: https://github.com/fabiangreffrath/woof/commit/2dc65df5de6284cd636641b003ce2024e34668a5

> It's fixed for the non-dynamic modes now, but still can appear in "High" mode depending on the current scale.

Can you run `woof -verbose` and catch at what resolutions it happens?

Do you build a debug version? Dynamic resolution in debug is very slow. You can try artifacts: https://github.com/fabiangreffrath/woof/actions/runs/7231380708

**Comment by bangstk** [comment]
> Maybe fixed here: [2dc65df](https://github.com/fabiangreffrath/woof/commit/2dc65df5de6284cd636641b003ce2024e34668a5)
Ok, there's no longer any jumps between Single/Double/Triple. But, in "High" it still bobs up and down the same.

I use a release build; it's not running slow. Eviternity Map26 is just famously taxing for a software renderer, being a super large and detailed map. When looking at the main tower only a 2x scale will run at 144fps on my machine, anything higher and the framerate drops until turning to put it out of view.

Therefore it makes a good test for the dynamic resolution scaling.

> Can you run `woof -verbose` and catch at what resolutions it happens?
That doesn't seem to create any output even if I run it from a command line.
However, using "RATE" cheat I've caught a few though not exhaustive:
-1280x601
-1488x699
-1520x713
-1536x720
-1536x721

Also, the artifact you linked gives another symptom: now that linear sky is enabled again, linear sky X scale is also varying along with the vertical view. It also seems too wide in general.

https://www.dropbox.com/scl/fi/gtji2a50g2rqv66jv95g1/woof_2023-12-16_06-42-28.mp4?rlkey=rnslrqepdfdvqztsymsltf0f5&dl=0

I think maybe there's just too many ints/fixed/float conversions and such involved in all the various scaling calculations that using fractional dynamic scale factors might not be the best idea.

**Comment by rfomin** [comment]
>-1280x601
-1488x699
-1520x713
-1536x720
-1536x721

It seems we have to make height even too: https://github.com/fabiangreffrath/woof/commit/6a214d5b9c3b8208d3b713156f230aa9a467b459

> > Can you run `woof -verbose` and catch at what resolutions it happens?
> 
> That doesn't seem to create any output even if I run it from a command line.

Terminal output is enabled in `woof.com`, `woof.exe` does not output anything to the default console.

> When looking at the main tower only a 2x scale will run at 144fps on my machine, anything higher and the framerate drops until turning to put it out of view.

Oh, dynamic resolution scaling (DRS) is targeting 144 FPS, maybe that's too much.

> I think maybe there's just a lot of calculations involving ints/fixed/float conversions that using fractional scale values ends up with truncation and rounding errors in a lot of cases. But this is probably the best way to find them all.

Yes, Doom operates with fixed math in 16.16 format (16 bits integer part, 16 bits fractional part). We want to keep it to preserve various rendering artefacts, so I'm not sure if we can get rid of that twitching. I think we should make DRS more conservative, max 60 FPS, minimum 600p resolution. Try playing around with these parameters: https://github.com/fabiangreffrath/woof/blob/6a214d5b9c3b8208d3b713156f230aa9a467b459/src/i_video.c#L505-L508 E.g. try to set `DRS_MIN_HEIGHT` to 600. I'm interested in the feedback.

**Comment by bangstk** [comment]
I think what I would try is to make the dynamic scaling only work in whole numbers rather than fractional multipliers (e.g. it goes 4x, 5x, 6x, etc instead of 4.1, 4.2, 4.3 as it increases)

**Comment by bangstk** [comment]
Ok, limiting the scaling to factors of 0.5 avoids any of the vertical look jumping.

Factors of 1.0 makes the status bar almost totally constant (though it is still getting a little bit of rounding error as the scale changes)

The linear sky does still pop around sometimes in either case.

The reduction rate from FPS method may need tweaking because it could be more liable to get stuck in hysteresis more with less granular scale steps. But I think you might have better ideas for adjusting that.

Here's what I did:

```diff
diff --git a/src/i_video.c b/src/i_video.c
index b8f3910..e9ce929 100644
--- a/src/i_video.c
+++ b/src/i_video.c
@@ -477,6 +477,7 @@ static void UpdateRender(void)
 }
 
 static uint64_t frametime_withoutpresent;
+static int fracheight = -1;
 
 static void ResetResolution(int height);
 static void ResetLogicalSize(void);
@@ -504,35 +505,46 @@ static void DynamicResolution(void)
     #define DRS_DELTA 0.5
     #define DRS_GREATER (1 + DRS_DELTA)
     #define DRS_LESS (1 - DRS_DELTA)
+    #define DRS_STEP SCREENHEIGHT // / 2
 
     int newheight = 0;
     int oldheight = video.height;
+    if (fracheight == -1)
+    {
+        fracheight = video.height;
+        I_Printf(VB_WARNING, "seeded fracheight");
+    }
 
     if (actualpercent > DRS_GREATER)
     {
         double reduction = (actualpercent - DRS_GREATER ) * 0.2;
-        newheight = (int)MAX(DRS_MIN_HEIGHT, oldheight - oldheight * reduction);
+        newheight = (int)MAX(DRS_MIN_HEIGHT, fracheight - fracheight * reduction);
     }
     else if (actualpercent < DRS_LESS)
     {
         double addition = (DRS_LESS - actualpercent) * 0.25;
-        newheight = (int)MIN(native_height_adjusted, oldheight + oldheight * addition);
+        newheight = (int)MIN(native_height_adjusted, fracheight + fracheight * addition);
     }
     else
     {
         return;
     }
 
+    fracheight = newheight;
+    newheight = newheight - newheight % DRS_STEP;
+
+    I_Printf(VB_WARNING, "newheight %d fracheight %d", newheight, fracheight);
+
     if (newheight == oldheight)
     {
         return;
     }
 
+    if (newheight < DRS_MIN_HEIGHT)
     {
+        newheight = DRS_MIN_HEIGHT;
     }
 
     ResetResolution(newheight);
```

Leave as is for 1.0 scale steps, Add the / 2 to the end of DRS_STEP to make it scale in steps of 0.5.

You can probably do this in a better way but this should be enough to demonstrate it.

**Comment by rfomin** [comment]
Interestingly, your parameters almost completely disable DRS on my system. I get decent results with `DRS_STEP (SCREENHEIGHT / 4)` and `DRS_DELTA 0,1`. But I agree, we should use much larger steps and make the scaling multipliers close to integer. It makes DRS boring, but a stable image is much more important. Thanks for the research!

**Comment by bangstk** [comment]
Oh and one more issue:
If you turn on the classic 35FPS cap DRS goes for the lowest resolution (it probably thinks the game is lagging)

**Comment by rfomin** [comment]
> If you turn on the classic 35FPS cap DRS goes for the lowest resolution (it probably thinks the game is lagging)

This is because in the case of 35FPS, the frame limiter is in the `TryRunTics` function. I'm working on it.

**Comment by bangstk** [comment]
With this minor tweak I was able to clean up the slight rounding errors at "Triple" resolution:

```diff
diff --git a/src/i_video.c b/src/i_video.c
--- a/src/i_video.c
+++ b/src/i_video.c
@@ -974,6 +991,7 @@ static void I_GetWindowPosition(int *x, int *y, int w, int h)
 static void ResetResolution(int height)
 {
     int w, h;
+    double vertscale;

     if (height > native_height_adjusted)
     {
@@ -982,6 +1000,7 @@ static void ResetResolution(int height)

     actualheight = use_aspect ? (int)(height * 1.2) : height;
     video.height = height;
+    vertscale = (double)actualheight / ACTUALHEIGHT;

     if (widescreen)
     {
@@ -1019,7 +1038,7 @@ static void ResetResolution(int height)
     }

     video.unscaledw = (int)(ACTUALHEIGHT * aspect_ratio);
-    video.width = (int)(actualheight * aspect_ratio);
+    video.width = (int)(video.unscaledw * vertscale);

     // width and height shoud be even
     video.unscaledw = (video.unscaledw  + 1) & ~1;
```

Now when cycling from single all the way to triple (or my integer scaling only modified version of High) the status bar & HUD doesn't shift around even 1 pixel anywhere. 

Essentially with video.width not dependent on video.unscaledw, it ended up adding a few extra pixels to the sides at higher scales, making it no longer an integer scale from 320x200 (or whatever current widescreen equivalent)

The first person weapon sprite still does shift/stretch a tiny bit on Triple, but it's progress.

**Comment by rfomin** [comment]
After tinkering and testing, I decided to implement all of what you suggested here: https://github.com/fabiangreffrath/woof/pull/1345 artifacts: https://github.com/fabiangreffrath/woof/actions/runs/7272604441 (automap is broken for now)

Works much better, thank you!

**Comment by bangstk** [comment]
Thanks, the scaling is even now and vertical mouselook isnt jumping up or down!

But, I think the algorithm for deciding when to move up/down in scale might need tweaking with the new step size. On my 165Hz screen with those artifacts I am now almost always caught in a hysteresis where it is going back and forth between scale steps every other frame. It's harder to tell now that the pixels are pretty even but the switching causes its own slowdown.

This is whether it's on Doom 2 Map01 or the Eviternity Map26 example.

**Comment by rfomin** [comment]
> On my 165Hz screen with those artifacts I am now almost always caught in a hysteresis where it is going back and forth between scale steps every other frame. It's harder to tell now that the pixels are pretty even but the switching causes its own slowdown.

It seems I'm currently too optimistic about the hysteresis, try setting `#define DRS_DELTA 0.01` to `0.1` or `0.5`.

**Comment by bangstk** [comment]
Oh, from looking at the code, I have a guess. In my experiment version above, I saved 'newheight' to a temp variable before rounding it to integer and used that temp for the scale reduction/increase calculation instead of oldheight (video.height).

This because if it calculates based on the currently integer reduced video.height, it's calculating based on something that was a lot lower than its reduction target, so it decides it's time to go back up again after that.

**Comment by rfomin** [comment]
Have you tried `DRS_DELTA 0.1`?

**Comment by bangstk** [comment]
I just tried the new artifact where you committed that. It's still doing it.

I'll play around with the code myself later.
It's a tough challenge really - this is basically controls math.

For what it's worth, it's only really happening if I have a framerate limit set above 100 or so. Below that (such as 60) it seems pretty rock solid.

[Unreal Engine[(https://docs.unrealengine.com/4.26/en-US/RenderingAndGraphics/DynamicResolution/) goes into good detail about how its DRS algorithm works. Some ideas from it are:
-It keeps a history buffer of the last n frametimes
-If enough of those frames are too slow, then it will drop the scale quick
-After a drop, scale gradually increases until the frame times are back 'in budget'

**Comment by rfomin** [comment]
I think this is fixed in https://github.com/fabiangreffrath/woof/commit/e4464862c5255435ed7360f31e4c891bd6b1a086 Thank you for the suggestions, I'm still interested in getting feedback.

**Comment by bangstk** [comment]
I am away on vacation until the end of next week, I'll let you know then

**Comment by bangstk** [comment]
Ok, I tried out a [447057b](https://github.com/fabiangreffrath/woof/commit/447057bd3af1b31087d3e5974ff7c2761cdb78a6) build.

- There is still a hysteresis loop. Now instead of the scale changing every frame, it is going up for 1 frame, then going down, staying stable for 1 second before repeating. But, it's a lot less distracting than before at least!
- With the scale steps now 50px, vertical view angle jumps around again

I think the case of "running at maximum fps" kind of causes a conflict of interest.

If the game is running at the refresh rate, it will go up a scale step.
But, if it gets there, and now it's a bit too slow, it will go down a scale step.
This kind of inherently is an infinite loop.

Another thought: every time the scale changes, the game has to recalculate some lookup tables which vary with resolution (ylookup, yslopes, etc) and the time spent doing this at high resolutions might cause that first frame of a new scale to be slower than what it would really run at afterward. Essentially creating a false negative for the game being able to run fast enough at that scale.

I wonder why you don't have either of theses happening on your own 1440p/144hz setup.
What cpu do you have? I have an i7-9900k at stock clocks.

**Comment by fabiangreffrath** [comment]
Maybe the logic should be changed from "react of target frame rate could not be maintained" to "react only if frame rate is beneath a specific threshold for some significant time".

**Comment by fabiangreffrath** [comment]
In other words, I think we need to pull the thresholds further apart than +/-10% around the target frame rate.

**Comment by rfomin** [comment]
> I wonder why you don't have this happening on your own 1440p/144hz setup.
> What cpu do you have? I have an i7-9900k at stock clocks.

I have a Core i5-12400F which maintains maximum resolution and 130+ FPS most of the time. There are extreme maps where it drops the resolution to 400p (e.g. beginning of "Eviternity II RC5.wad" MAP11).

> At Doom 2 Map01 in starting position in fullscreen, RATE shows it sits at between 700p-850p height during the 1 second waits, and instantly bounces off of 1000p-1050p height every second back to 700p-850p.

My guess is that you are using debug versions of SDL. Have you tried artifacts? Anyway, to improve this we can try lowering `DRS_DELTA` to `0.01`, then it shouldn't try to increase the resolution all the time.

> * With the scale steps now 50px, vertical view angle jumps around again

Is it better at 100px? It's fine at 200px, but then DRS is of little use at 1080p and lower resolutions (it only has 2-3 steps). Perhaps we can improve the calculation of `yslopes`.

> It may need something more than just frametime to be a good predictor. Maybe a precipitous drop in segs/visplanes or such could be a trigger that it's time to try scaling up.

As I understand it, we know the number of segs at the end of the frame rendering, so it's not much different from the frame time.

> Another thought: every time the scale changes, the game has to recalculate some lookup tables which vary with resolution (ylookup, yslopes, etc)

This recalculation is fast. I tried to improve the speed of resolution switching, we allocate most of the arrays only once for the native resolution. When we change the resolution, we change the logical size (`SDL_RenderSetLogicalSize`) and recreate the textures for the "smooth pixel scaling" feature. On my slow 10+ year old laptop, `ResetResolution` function runs in ~30 microseconds.

> In other words, I think we need to pull the thresholds further apart than +/-10% around the target frame rate.

I think to maintain a stable FPS we have to react even faster, perhaps ahead of time somehow. Even a single slow frame is noticeable with 60Hz vsync. But maybe we should increase the resolution slower.

I am currently planning to add a "Resolution Scale" slider to the menu with a DRS option underneath it, where the user can set the maximum resolution for DRS. The default max resolution will be 600p, I think it will be stable on most CPUs.

**Comment by fabiangreffrath** [comment]
I don't have the slowest PC (i5-1235U), but this is what happened on a run through MAP01:

```
ResetResolution: 1918x900
S_ChangeMusic: D_DM2TTL (doom2.wad)
S_ChangeMusic: D_RUNNIN (doom2.wad)
P_SetupLevel: MAP01 (doom2.wad), Skill 4, Doom, MBF21
ResetResolution: 1704x800
ResetResolution: 1918x900
ResetResolution: 1704x800
ResetResolution: 1598x750
ResetResolution: 1918x900
ResetResolution: 1704x800
ResetResolution: 1918x900
ResetResolution: 1704x800
S_ChangeMusic: D_DM2INT (doom2.wad)
S_ChangeMusic: D_STALKS (doom2.wad)
P_SetupLevel: MAP02 (doom2.wad), Skill 4, Doom, MBF21
```

So, it changes the resolution 9 times on the most simple map imaginable. Granted, I didn't recognize any of these switches. Feels a bit strange nevertheless.

**Comment by rfomin** [comment]
> So, it changes the resolution 9 times on the most simple map imaginable. Granted, I didn't recognize any of these switches.

Just finished MAP01 on my slow laptop with the current master, the resolution only switched once at the beginning. Hmm, did you change the frame limiter? VSync?

Anyway, if the switches are unrecognizable, I consider mission accomplished 😄 Users who are annoyed by it can just turn it off. Not sure perfection is achievable.

I saw that PrBoom+ has a different mouselook implementation, I think we can avoid the `yslopes` recalculation.

**Comment by fabiangreffrath** [comment]
Yes, I have vsync enabled all the time.

**Comment by rfomin** [comment]
> Yes, I have vsync enabled all the time.

60 Hz? Is it a mobile processor? Maybe it's trying to save energy? No other ideas yet, it looks much more powerful than my laptop. My desktop only lowers the resolution on very complex maps.

**Comment by fabiangreffrath** [comment]
Yes 60Hz, yes mobile CPU, yes running on battery.

**Comment by fabiangreffrath** [comment]
Sorry if this is the most stupid question possible, but is vsync at 60hz a problem?

**Comment by rfomin** [comment]
> Sorry if this is the most stupid question possible, but is vsync at 60hz a problem?

It's Linux, right? I'm not sure, but it should be fine. I asked in case you have a monitor with a high refresh rate. If the refresh rate is 144Hz, you need a pretty powerful CPU and no power saving plan enabled to maintain high resolution.

**Comment by fabiangreffrath** [comment]
Okay, so it's not that we are targeting a frame rate that's higher and that we just cannot achieve because of vsync.

**Comment by rfomin** [comment]
> Okay, so it's not that we are targeting a frame rate that's higher and that we just cannot achieve because of vsync.

I am trying to avoid this by assuming that waiting for vsync happens in `SDL_RenderPresent` function (`frametime_withoutpresent` variable). It seems to work this way on Win10.

**Comment by bangstk** [comment]
Here's the actual log of me at MAP01:
```
ResetResolution: 1820x850
ResetResolution: 2248x1050
ResetResolution: 1820x850
ResetResolution: 2248x1050
ResetResolution: 1928x900
ResetResolution: 1820x850
ResetResolution: 2248x1050
ResetResolution: 1928x900
ResetResolution: 1820x850
ResetResolution: 2248x1050
ResetResolution: 1928x900
ResetResolution: 1820x850
```

> This recalculation is fast. On my slow 10+ year old laptop, `R_ExecuteSetViewSize` function runs in ~2-3 ms. We can pre-calculate it for each step because we don't have many, especially with `DRS_STEP 100`.

Note that 144Hz is about 7 ms frametime, so adding 2-3ms on top of that adds enough delay to be the same frametime as 100hz, which is a big jump from 144. I know your time measurement was from an old laptop, but what resolution was that laptop calculating it for? The lookup table sizes get bigger with resolution.

Also, for me it happens with vsync off as well.

It should be noted that Windows enforces Vsync unless an application is exclusive fullscreen. However it happens to me there as well.

> My guess is that you are using debug versions of SDL. Have you tried artifacts? Anyway, to improve this we can try lowering `DRS_DELTA` to `0.01`, then it shouldn't try to increase the resolution all the time.

Nope, I am using the artifacts from the 'Actions' tab, so it's the SDL that's built in.

> Is it better at 100px? It's fine at 200px, but then DRS is of little use at 1080p and lower resolutions (it only has 2-3 steps). Perhaps we can improve the calculation of `yslopes`.

There's no view jumping around at 100px.

**Comment by rfomin** [comment]
> I am running at about ~250fps at 850p scale, so I really think it's the hitch from recalculating the tables that is keeping it from staying at 1000p+ or even 900p. If it were allowed to run a couple frames longer before the scale drops then it might stay below the frametime target.

I modelled this problem on my laptop by running it at a high frame rate. After a few tests, the table recalculation does seem slow. I think we can speed it up by half with a different implementation of mouselook. Alternatively, we can just ignore the first `frametime` after the resolution reset. As a last resort, we can precompute all the tables for all the steps (not really wasting that much memory). I'll try that in the near future.

**Comment by fabiangreffrath** [comment]
> just ignore the first `frametime` after the resolution reset

This seems perfectly reasonable.

**Comment by fabiangreffrath** [comment]
May we consider this as fixed with this commit?
https://github.com/fabiangreffrath/woof/commit/e6c8b4d56eed36a5aa8481b298ad2bde361d12cf

**Comment by rfomin** [comment]
> May we consider this as fixed with this commit?

Not sure. I also want to add resolution scaling options to the menu, and make default settings more conservative. I'm working on it.

**Comment by MrAlaux** [comment]
I'm getting the HOM on the right edge of the screen in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/7765994278), specifically with widescreen disabled -- enabling it makes the HOM disappear:
![imagen](https://github.com/fabiangreffrath/woof/assets/73968015/18b25725-a6c2-4318-9d78-fcb343ed002b)

**Comment by rfomin** [comment]
Most issue have been fixed or improved.
