### ISSUE TITLE
The latest release (and master branch) fails to build under Arch Linux

### ISSUE THREAD

**Issue by Zse00** [fabiangreffrath/woof#761]
[****@archbook projects]$ git clone https://github.com/fabiangreffrath/woof.git
Cloning into 'woof'...
remote: Enumerating objects: 7332, done.
remote: Counting objects: 100% (409/409), done.
remote: Compressing objects: 100% (249/249), done.
remote: Total 7332 (delta 246), reused 281 (delta 160), pack-reused 6923
Receiving objects: 100% (7332/7332), 12.38 MiB | 19.09 MiB/s, done.
Resolving deltas: 100% (5481/5481), done.
[****@archbook projects]$ mkdir ./woof/build && cd ./woof/build
[****@archbook build]$ cmake .. && make -j8
-- The C compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Setting build type to 'RelWithDebInfo' as none was specified.
-- Looking for pow in m
-- Looking for pow in m - found
-- Looking for dirent.h
-- Looking for dirent.h - found
-- Looking for strsignal
-- Looking for strsignal - found
-- Looking for strcasecmp
-- Looking for strcasecmp - found
-- Looking for strncasecmp
-- Looking for strncasecmp - found
-- Found SDL2: /usr/include/SDL2 (found suitable version "2.24.0", minimum required is "2.0.7") 
-- Found SDL2_mixer: /usr/include/SDL2 (found suitable version "2.6.2", minimum required is "2.0.2") 
-- Found SDL2_net: /usr/include/SDL2 (found version "2.2.0") 
-- Found FluidSynth: /lib/libfluidsynth.so (found version "1.1.6") 
-- Found Python3: /usr/bin/python3.10 (found version "3.10.7") found components: Interpreter 
-- Performing Test CFLAG_Wdeclaration-after-statement
-- Performing Test CFLAG_Wdeclaration-after-statement - Success
-- Performing Test CFLAG_Werror_implicit-function-declaration
-- Performing Test CFLAG_Werror_implicit-function-declaration - Success
-- Performing Test CFLAG_Werror_incompatible-pointer-types
-- Performing Test CFLAG_Werror_incompatible-pointer-types - Success
-- Performing Test CFLAG_Werror_int-conversion
-- Performing Test CFLAG_Werror_int-conversion - Success
-- Performing Test CFLAG_Wformat_2
-- Performing Test CFLAG_Wformat_2 - Success
-- Performing Test CFLAG_Wnull-dereference
-- Performing Test CFLAG_Wnull-dereference - Success
-- Performing Test CFLAG_Wredundant-decls
-- Performing Test CFLAG_Wredundant-decls - Success
-- Performing Test CFLAG_Wrestrict
-- Performing Test CFLAG_Wrestrict - Success
-- Performing Test CFLAG_Wall
-- Performing Test CFLAG_Wall - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/unyx/projects/woof/build
[  3%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_checkbox.c.o
[  3%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_desktop.c.o
[  4%] Building C object opl/CMakeFiles/opl.dir/opl.c.o
[  4%] Building C object opl/CMakeFiles/opl.dir/opl_sdl.c.o
[  3%] Building C object opl/CMakeFiles/opl.dir/opl_queue.c.o
[  5%] Building C object opl/CMakeFiles/opl.dir/opl3.c.o
[  5%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_button.c.o
[  5%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_dropdown.c.o
[  6%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_gui.c.o
[  7%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_io.c.o
[  7%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_inputbox.c.o
[  8%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_fileselect.c.o
[  9%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_label.c.o
[ 10%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_scrollpane.c.o
[ 10%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_separator.c.o
[ 11%] Linking C static library libopl.a
[ 12%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_strut.c.o
[ 12%] Built target opl
[ 12%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_table.c.o
[ 13%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_widget.c.o
[ 14%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_window_action.c.o
[ 14%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_window.c.o
[ 15%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_sdl.c.o
[ 16%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_utf8.c.o
[ 16%] Linking C static library libtextscreen.a
[ 16%] Built target textscreen
[ 17%] Building C object setup/CMakeFiles/setup.dir/multiplayer.c.o
[ 17%] Building C object setup/CMakeFiles/setup.dir/mainmenu.c.o
[ 18%] Building C object setup/CMakeFiles/setup.dir/execute.c.o
[ 20%] Building C object src/CMakeFiles/woof.dir/am_map.c.o
[ 19%] Building C object src/CMakeFiles/woof.dir/d_deh.c.o
[ 21%] Building C object src/CMakeFiles/woof.dir/d_items.c.o
[ 22%] Building C object src/CMakeFiles/woof.dir/d_main.c.o
[ 22%] Building C object src/CMakeFiles/woof.dir/d_iwad.c.o
[ 23%] Building C object src/CMakeFiles/woof.dir/d_loop.c.o
[ 23%] Building C object src/CMakeFiles/woof.dir/d_net.c.o
[ 25%] Building C object src/CMakeFiles/woof.dir/d_quit.c.o
[ 26%] Building C object src/CMakeFiles/woof.dir/doomdef.c.o
[ 26%] Building C object src/CMakeFiles/woof.dir/doomstat.c.o
[ 27%] Building C object src/CMakeFiles/woof.dir/dsdhacked.c.o
[ 28%] Building C object src/CMakeFiles/woof.dir/dstrings.c.o
[ 28%] Building C object src/CMakeFiles/woof.dir/f_finale.c.o
[ 29%] Building C object src/CMakeFiles/woof.dir/f_wipe.c.o
[ 30%] Building C object src/CMakeFiles/woof.dir/g_game.c.o
[ 30%] Building C object src/CMakeFiles/woof.dir/hu_lib.c.o
[ 31%] Building C object src/CMakeFiles/woof.dir/hu_stuff.c.o
[ 32%] Building C object src/CMakeFiles/woof.dir/i_endoom.c.o
[ 32%] Linking C static library libsetup.a
[ 32%] Building C object src/CMakeFiles/woof.dir/i_flmusic.c.o
[ 33%] Building C object src/CMakeFiles/woof.dir/i_glob.c.o
[ 33%] Built target setup
[ 34%] Building C object src/CMakeFiles/woof.dir/i_main.c.o
[ 34%] Building C object src/CMakeFiles/woof.dir/i_oplmusic.c.o
[ 35%] Building C object src/CMakeFiles/woof.dir/i_sdlmusic.c.o
[ 36%] Building C object src/CMakeFiles/woof.dir/i_sound.c.o
[ 36%] Building C object src/CMakeFiles/woof.dir/i_system.c.o
[ 37%] Building C object src/CMakeFiles/woof.dir/i_timer.c.o
/home/unyx/projects/woof/src/i_flmusic.c: In function ‘I_FL_InitMusic’:
/home/unyx/projects/woof/src/i_flmusic.c:141:20: error: implicit declaration of function ‘new_fluid_defsfloader’; did you mean ‘new_fluid_player’? [-Werror=implicit-function-declaration]
  141 |         sfloader = new_fluid_defsfloader(settings);
      |                    ^~~~~~~~~~~~~~~~~~~~~
      |                    new_fluid_player
/home/unyx/projects/woof/src/i_flmusic.c:141:18: error: assignment to ‘fluid_sfloader_t *’ {aka ‘struct _fluid_sfloader_t *’} from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
  141 |         sfloader = new_fluid_defsfloader(settings);
      |                  ^
[ 38%] Building C object src/CMakeFiles/woof.dir/i_video.c.o
/home/unyx/projects/woof/src/i_flmusic.c:142:9: error: implicit declaration of function ‘fluid_sfloader_set_callbacks’ [-Werror=implicit-function-declaration]
  142 |         fluid_sfloader_set_callbacks(sfloader, FL_sfopen, FL_sfread, FL_sfseek,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
[ 38%] Building C object src/CMakeFiles/woof.dir/info.c.o
make[2]: *** [src/CMakeFiles/woof.dir/build.make:328: src/CMakeFiles/woof.dir/i_flmusic.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 39%] Building C object src/CMakeFiles/woof-setup.dir/i_main.c.o
[ 39%] Building C object src/CMakeFiles/woof-setup.dir/i_system.c.o
[ 40%] Building C object src/CMakeFiles/woof-setup.dir/i_timer.c.o
[ 41%] Building C object src/CMakeFiles/woof-setup.dir/m_argv.c.o
[ 41%] Building C object src/CMakeFiles/woof-setup.dir/m_misc2.c.o
[ 42%] Building C object src/CMakeFiles/woof-setup.dir/m_io.c.o
[ 42%] Building C object src/CMakeFiles/woof-setup.dir/net_io.c.o
[ 43%] Building C object src/CMakeFiles/woof-setup.dir/d_iwad.c.o
[ 44%] Building C object src/CMakeFiles/woof-setup.dir/net_packet.c.o
[ 45%] Building C object src/CMakeFiles/woof-setup.dir/net_sdl.c.o
[ 45%] Building C object src/CMakeFiles/woof-setup.dir/net_query.c.o
[ 46%] Building C object src/CMakeFiles/woof-setup.dir/net_structrw.c.o
[ 47%] Building C object src/CMakeFiles/woof-setup.dir/z_zone.c.o
make[1]: *** [CMakeFiles/Makefile2:263: src/CMakeFiles/woof.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 48%] Linking C executable woof-setup
[ 48%] Built target woof-setup
make: *** [Makefile:156: all] Error 2
[****@archbook build]$

**Comment by fabiangreffrath** [comment]
> -- Found FluidSynth: /lib/libfluidsynth.so (found version "1.1.6")

Any chance to upgrade to version 2 or higher?

**Comment by Zse00** [comment]
My package manager says I'm on 2.3.0-2

a Quick locate command for libfluidsynth.so found these:
/usr/lib/libfluidsynth.so
/usr/lib/libfluidsynth.so.3
/usr/lib/libfluidsynth.so.3.1.3

**Comment by rfomin** [comment]
Maybe this patch will work:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 0c7115b..79bac04 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -172,7 +172,8 @@ if (NOT FluidSynth_DIR)
         set(FluidSynth_DIR "${CMAKE_CURRENT_BINARY_DIR}/fluidsynth-${pkgver}")
     endif()
 endif()
-find_package(FluidSynth)
+# 2.2.0 for unicode fopen on Windows
+find_package(FluidSynth 2.2.0)
 
 # Python 3
 find_package(Python3 COMPONENTS Interpreter)
diff --git a/cmake/FindFluidSynth.cmake b/cmake/FindFluidSynth.cmake
index b0121ab..683680c 100644
--- a/cmake/FindFluidSynth.cmake
+++ b/cmake/FindFluidSynth.cmake
@@ -59,11 +59,6 @@
 set(FluidSynth_DIR "${FluidSynth_DIR}"
         CACHE PATH "Location of FluidSynth library directory")
 
-if(NOT ${FluidSynth_FIND_VERSION})
-  # 2.2.0 for unicode fopen on Windows
-  set(FluidSynth_FIND_VERSION "2.2.0")
-endif()
-
 find_package(PkgConfig QUIET)
 pkg_check_modules(PC_FluidSynth QUIET fluidsynth>=${FluidSynth_FIND_VERSION})
 
```

**Comment by fabiangreffrath** [comment]
> My package manager says I'm on 2.3.0-2
> 
> a Quick locate command for libfluidsynth.so on my system found these: /usr/lib/libfluidsynth.so /usr/lib/libfluidsynth.so.3 /usr/lib/libfluidsynth.so.3.1.3

That's `/usr/lib`, but you seem to have an older copy in `/lib`.

**Comment by fabiangreffrath** [comment]
> Maybe this patch will work:

If we use API from version 2.2, we should explicitly require that version,  sure.

**Comment by rfomin** [comment]
> If we use API from version 2.2, we should explicitly require that version, sure.

Fluidsynth prior to 2.2.0 could not open a soundfont with a non-latin path on Windows. I don't know about the actual API, maybe > 2.0.0.

**Comment by fabiangreffrath** [comment]
If we know 2.2 works and older versions may not, let's require the newer one.

**Comment by Zse00** [comment]
> > My package manager says I'm on 2.3.0-2
> > a Quick locate command for libfluidsynth.so on my system found these: /usr/lib/libfluidsynth.so /usr/lib/libfluidsynth.so.3 /usr/lib/libfluidsynth.so.3.1.3
> 
> That's `/usr/lib`, but you seem to have an older copy in `/lib`.

On my system `/lib` is just a sym link to `/usr/lib` so far as I know they should contain the exact same thing and my pacman puts all lib files in /usr/bin, correct me if I'm wrong

**Comment by fabiangreffrath** [comment]
> correct me if I'm wrong

Obviously, i can't tell you details about your system, but i can tell for sure that Woof compiles on Arch Linux. Here's the AUR page:

https://aur.archlinux.org/packages/woof-git

@rfomin would you please like to commit the patch you posted earlier?

**Comment by rfomin** [comment]
> @rfomin would you please like to commit the patch you posted earlier?

Done in https://github.com/fabiangreffrath/woof/commit/5f232babaa96479785afdce26c765f00843dcfa5

**Comment by fabiangreffrath** [comment]
@Zse00 could you please attempt another build with the latest git snapshot?

**Comment by Zse00** [comment]
> @Zse00 could you please attempt another build with the latest git snapshot?

Preparing...
Cloning woof-git build files...
Generating woof-git information...
Checking woof-git dependencies...
Resolving dependencies...
Checking inter-conflicts...

Building woof-git...
==> Making package: woof-git 10.3.0.r22.de41b6c-1 (dim. 09 oct. 2022 15:03:01)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning woof git repo...
Cloning into bare repository '/var/tmp/pamac-build-unyx/woof-git/woof'...
==> Validating source files with sha512sums...
    woof ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of woof git repo...
Cloning into 'woof'...
done.
==> Starting prepare()...
-- The C compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Setting build type to 'RelWithDebInfo' as none was specified.
-- Looking for pow in m
-- Looking for pow in m - found
-- Looking for dirent.h
-- Looking for dirent.h - found
-- Looking for strsignal
-- Looking for strsignal - found
-- Looking for strcasecmp
-- Looking for strcasecmp - found
-- Looking for strncasecmp
-- Looking for strncasecmp - found
-- Found SDL2: /usr/include/SDL2 (found suitable version "2.24.0", minimum required is "2.0.7") 
-- Found SDL2_mixer: /usr/include/SDL2 (found suitable version "2.6.2", minimum required is "2.0.2") 
-- Found SDL2_net: /usr/include/SDL2 (found version "2.2.0") 
-- Found FluidSynth: /lib/libfluidsynth.so (found suitable version "2.3.0", minimum required is "2.2.0") 
-- Found Python3: /usr/bin/python3.10 (found version "3.10.7") found components: Interpreter 
-- Performing Test CFLAG_Wdeclaration-after-statement
-- Performing Test CFLAG_Wdeclaration-after-statement - Success
-- Performing Test CFLAG_Werror_implicit-function-declaration
-- Performing Test CFLAG_Werror_implicit-function-declaration - Success
-- Performing Test CFLAG_Werror_incompatible-pointer-types
-- Performing Test CFLAG_Werror_incompatible-pointer-types - Success
-- Performing Test CFLAG_Werror_int-conversion
-- Performing Test CFLAG_Werror_int-conversion - Success
-- Performing Test CFLAG_Wformat_2
-- Performing Test CFLAG_Wformat_2 - Success
-- Performing Test CFLAG_Wnull-dereference
-- Performing Test CFLAG_Wnull-dereference - Success
-- Performing Test CFLAG_Wredundant-decls
-- Performing Test CFLAG_Wredundant-decls - Success
-- Performing Test CFLAG_Wrestrict
-- Performing Test CFLAG_Wrestrict - Success
-- Performing Test CFLAG_Wall
-- Performing Test CFLAG_Wall - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /var/tmp/pamac-build-unyx/woof-git/src/woof-build
==> Starting pkgver()...
==> Starting build()...
[  2%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_button.c.o
[  2%] Building C object opl/CMakeFiles/opl.dir/opl.c.o
[  2%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_checkbox.c.o
[  3%] Building C object opl/CMakeFiles/opl.dir/opl_sdl.c.o
[  3%] Building C object opl/CMakeFiles/opl.dir/opl_queue.c.o
[  4%] Building C object opl/CMakeFiles/opl.dir/opl3.c.o
[  5%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_desktop.c.o
[  5%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_dropdown.c.o
[  6%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_gui.c.o
[  7%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_io.c.o
[  7%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_inputbox.c.o
[  8%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_label.c.o
[  9%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_fileselect.c.o
[  9%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_separator.c.o
[ 10%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_strut.c.o
[ 11%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_table.c.o
[ 11%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_scrollpane.c.o
[ 12%] Linking C static library libopl.a
[ 13%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_widget.c.o
[ 13%] Built target opl
[ 14%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_window_action.c.o
[ 14%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_window.c.o
[ 15%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_sdl.c.o
[ 16%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_utf8.c.o
[ 16%] Linking C static library libtextscreen.a
[ 16%] Built target textscreen
[ 17%] Building C object setup/CMakeFiles/setup.dir/execute.c.o
[ 17%] Building C object setup/CMakeFiles/setup.dir/mainmenu.c.o
[ 18%] Building C object src/CMakeFiles/woof.dir/am_map.c.o
[ 18%] Building C object src/CMakeFiles/woof.dir/d_iwad.c.o
[ 19%] Building C object src/CMakeFiles/woof.dir/d_items.c.o
[ 20%] Building C object src/CMakeFiles/woof.dir/d_main.c.o
[ 21%] Building C object setup/CMakeFiles/setup.dir/multiplayer.c.o
[ 22%] Building C object src/CMakeFiles/woof.dir/d_deh.c.o
[ 23%] Building C object src/CMakeFiles/woof.dir/d_loop.c.o
[ 23%] Building C object src/CMakeFiles/woof.dir/d_net.c.o
[ 25%] Building C object src/CMakeFiles/woof.dir/d_quit.c.o
[ 26%] Building C object src/CMakeFiles/woof.dir/doomdef.c.o
[ 26%] Building C object src/CMakeFiles/woof.dir/doomstat.c.o
[ 27%] Building C object src/CMakeFiles/woof.dir/dsdhacked.c.o
[ 28%] Building C object src/CMakeFiles/woof.dir/dstrings.c.o
[ 28%] Building C object src/CMakeFiles/woof.dir/f_finale.c.o
[ 29%] Building C object src/CMakeFiles/woof.dir/f_wipe.c.o
[ 30%] Building C object src/CMakeFiles/woof.dir/g_game.c.o
[ 30%] Building C object src/CMakeFiles/woof.dir/hu_lib.c.o
[ 31%] Building C object src/CMakeFiles/woof.dir/hu_stuff.c.o
[ 32%] Building C object src/CMakeFiles/woof.dir/i_endoom.c.o
[ 32%] Building C object src/CMakeFiles/woof.dir/i_flmusic.c.o
[ 33%] Building C object src/CMakeFiles/woof.dir/i_glob.c.o
[ 34%] Building C object src/CMakeFiles/woof.dir/i_main.c.o
[ 34%] Linking C static library libsetup.a
[ 34%] Building C object src/CMakeFiles/woof.dir/i_oplmusic.c.o
[ 35%] Building C object src/CMakeFiles/woof.dir/i_sdlmusic.c.o
[ 35%] Built target setup
[ 36%] Building C object src/CMakeFiles/woof.dir/i_sound.c.o
[ 37%] Building C object src/CMakeFiles/woof-setup.dir/i_main.c.o
[ 37%] Building C object src/CMakeFiles/woof-setup.dir/i_system.c.o
/var/tmp/pamac-build-unyx/woof-git/src/woof/src/i_flmusic.c: In function ‘I_FL_InitMusic’:
/var/tmp/pamac-build-unyx/woof-git/src/woof/src/i_flmusic.c:141:20: error: implicit declaration of function ‘new_fluid_defsfloader’; did you mean ‘new_fluid_player’? [-Werror=implicit-function-declaration]
  141 |         sfloader = new_fluid_defsfloader(settings);
      |                    ^~~~~~~~~~~~~~~~~~~~~
      |                    new_fluid_player
/var/tmp/pamac-build-unyx/woof-git/src/woof/src/i_flmusic.c:141:18: error: assignment to ‘fluid_sfloader_t *’ {aka ‘struct _fluid_sfloader_t *’} from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
  141 |         sfloader = new_fluid_defsfloader(settings);
      |                  ^
/var/tmp/pamac-build-unyx/woof-git/src/woof/src/i_flmusic.c:142:9: error: implicit declaration of function ‘fluid_sfloader_set_callbacks’ [-Werror=implicit-function-declaration]
  142 |         fluid_sfloader_set_callbacks(sfloader, FL_sfopen, FL_sfread, FL_sfseek,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 37%] Building C object src/CMakeFiles/woof.dir/i_system.c.o
[ 38%] Building C object src/CMakeFiles/woof.dir/i_timer.c.o
cc1: some warnings being treated as errors
make[2]: *** [src/CMakeFiles/woof.dir/build.make:328: src/CMakeFiles/woof.dir/i_flmusic.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 39%] Building C object src/CMakeFiles/woof-setup.dir/i_timer.c.o
[ 40%] Building C object src/CMakeFiles/woof-setup.dir/m_argv.c.o
[ 40%] Building C object src/CMakeFiles/woof-setup.dir/m_misc2.c.o
[ 41%] Building C object src/CMakeFiles/woof-setup.dir/m_io.c.o
[ 42%] Building C object src/CMakeFiles/woof-setup.dir/d_iwad.c.o
[ 42%] Building C object src/CMakeFiles/woof-setup.dir/net_io.c.o
[ 43%] Building C object src/CMakeFiles/woof-setup.dir/net_sdl.c.o
[ 43%] Building C object src/CMakeFiles/woof-setup.dir/net_query.c.o
[ 44%] Building C object src/CMakeFiles/woof-setup.dir/net_packet.c.o
[ 45%] Building C object src/CMakeFiles/woof-setup.dir/net_structrw.c.o
[ 46%] Building C object src/CMakeFiles/woof-setup.dir/z_zone.c.o
make[1]: *** [CMakeFiles/Makefile2:263: src/CMakeFiles/woof.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 47%] Linking C executable woof-setup
[ 47%] Built target woof-setup
make: *** [Makefile:156: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by fabiangreffrath** [comment]
You probably still have an old fluidsynth header installed on your system. What does this yield? (may take some time)
```
find / -name "fluidsynth.h"
```

**Comment by Zse00** [comment]
[archbook unyx]$ sudo !!                                                                                                                                                               
sudo find / -name "fluidsynth.h"

[sudo] password for unyx: 
/timeshift/snapshots/2022-10-08_18-25-45/localhost/usr/local/include/fluidsynth.h
/timeshift/snapshots/2022-10-08_18-25-45/localhost/usr/include/fluidsynth.h
/usr/local/include/fluidsynth.h
/usr/include/fluidsynth.h
find: ‘/run/user/1000/gvfs’: Permission denied
find: ‘/run/user/1000/doc’: Permission denied
[archbook unyx]$

**Comment by Zse00** [comment]
Yep, this was the issue. I ran a `doas mv /usr/local/include/fluidsynth.h /usr/local/include/fluidsynth.h.bak` and it fixed it. 
Thank You for the kind and quick help!

**Comment by fabiangreffrath** [comment]
Glad you got this resolved! 👍
